name: Bug 反馈
description: 报告一个可复现的问题
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: 问题描述
      description: 发生了什么？你期望的行为是什么？
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: 复现步骤
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: 日志/截图（可选）
  - type: input
    id: env
    attributes:
      label: 环境信息
      description: 浏览器/系统、是否酒馆环境、版本号等
